[package]
name = "rocket_jwt"
version = "0.1.0"
authors = ["Kjell W. Kongsvik <kjell.kongsvik@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
jsonwebtoken ="5"
serde_derive = "1"
serde = "1"
